### ISSUE TITLE
기업 회원 정보 수정 가능 목록 확인 요청

### ISSUE THREAD

**Issue by wjdals3936** [miracle-job-a/gateway-service#34]
기업 회원이 정보 수정이 가능한 데이터에 대해 확인하고 싶습니다.

현재 뷰로 확인 할 수 있는 정보들은 아래와 같습니다.
- 회사명
- 업종
- 대표자명
- 재직인원
- 사진
- 기업소개
- 상세주소
- 비밀번호

이 이외에도 bno가 변경될 가능성도 있다고 생각하는 데 bno 수정이 가능하도록 해야 할까요?
만약 그렇게 되면 bno 수정 시에 bno 승인 여부도 검사하면 될 것 같습니다.

하지만 저는 개인적으로는 bno가 변경된다면 재가입 시키는 게 맞다고 생각합니다.
이에 대해 의견 남겨주세요!
@kimjunyo @Hamel0

**Comment by kimjunyo** [comment]
사업자 번호는 변경될 경우는 주민등록번호와 같은 개념으로
만약에 변경될 경우에는 기업 쪽에서 새로 회원가입을 하는게 맞다고 생각합니다.

따라서, 사업자 번호는 수정이 가능하도록 하는 게 아닙니다.

**Comment by wjdals3936** [comment]
네 감사합니다.
