### ISSUE TITLE
면접 API 관련 질문

### ISSUE THREAD

**Issue by hazzokko** [miracle-job-a/gateway-service#36]
> What is issue

&nbsp;&nbsp; Sprint 3 면접 API 구현 추가 필요

<br>

> Problems

-  API 요청에 내용 입력해놨는데 확인해보시구 수정 필요하면 알려주세요!
- 그리고 면접 안의 질문&답 리스트를 5개 정도로 제한하는 것과 제한없이 입력하되 페이징 처리하는 것 중에서 선택해 주세요

<br>

> Notes

- figma에서 면접 리스트는 구현하지 않는 것으로 정리 하고 아래처럼 변경
  - 입사지원 현황 페이지에서 면접 - 이동 버튼을 클릭했을 때
    - 면접 정보가 존재하지 않으면 등록 페이지로 이동
    - 면접 정보가 존재하면 상세 조회 페이지로 이동 (해당 페이지에서 수정, 삭제 가능)

**Comment by kimjunyo** [comment]
5개로 제한하는 걸루 하는게 좋을거같아요
API 요청도 확인하였는데 좋습니다
