### ISSUE TITLE
기업 공고관리 페이지 정렬 메서드 수정 관련

### ISSUE THREAD

**Issue by Kade-Jeon** [miracle-job-a/gateway-service#38]
@kimjunyo @Hamel0 

현재 아래와 같이 4개의 경로로 나뉘어져 있습니다.
1. 최신순 조회 : /{companyId}/posts/latest?strNum=1&endNum=5
2. 마감임박순 조회 :  /{companyId}/posts/deadline?strNum=1&endNum=5
3. 마감공고만 보기 :  /{companyId}/posts/end?strNum=1&endNum=5
4. 진행중 공고만 보기 : /{companyId}/posts/open?strNum=1&endNum=5

위를 아래와 같이 1개 경로로 수정하고 파라미터로 처리되게끔 리팩토링할까 합니다.

/{companyId}/posts?strNum=1&endNum=5&sort=latest
/{companyId}/posts?strNum=1&endNum=5&sort=deadline
/{companyId}/posts?strNum=1&endNum=5&sort=close
/{companyId}/posts?strNum=1&endNum=5&sort=open

상의 후 코멘트 남겨주세요.

**Comment by kimjunyo** [comment]
이 부분은 코드 개발 미완성 단계이기 때문에
회의한 결과, 수정한 대로 진행하겠습니다.
